FROM registry.ci.openshift.org/ocp/builder:rhel-9-golang-1.26-openshift-5.0 AS builder
WORKDIR /go/src/github.com/openshift/local-storage-operator
COPY . .
RUN make build-operator-cover

FROM almalinux:9
COPY --from=builder /go/src/github.com/openshift/local-storage-operator/_output/bin/local-storage-operator /usr/bin/
COPY config/manifests /manifests
RUN mkdir -p /var/run/coverage
ENV GOCOVERDIR=/var/run/coverage
ENTRYPOINT ["/usr/bin/local-storage-operator"]
LABEL io.k8s.display-name="OpenShift local-storage-operator (coverage)" \
      io.k8s.description="Coverage-instrumented build for e2e test coverage measurement."
