apiVersion: "local.storage.openshift.io/v1"
kind: "LocalVolume"
metadata:
  name: "example"
spec:
  storageClassDevices:
    - storageClassName: "foobar"
      volumeMode: Filesystem
      fsType: ext4
      disoverAllLocalDevices:
        deviceTypes:
          - disk
          - part
          - crypt
          - lvmt
          - crypt
      devicePaths:
        - /dev/sandbox/local
